spring:
  application:
    name: mapstruct-spring
  messages:
    basename: locale/descriptions
    encoding: UTF-8
    fallback-to-system-locale: false

logging:
  level:
    org.springframework: INFO
